name: Latest iOS Apps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *' # Runs every two days

permissions:
  contents: write

jobs:
  update-readme-with-apps:
    name: Update README with latest iOS apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch iOS apps from App Store
        run: |
          # Replace with your actual Apple ID (usually your developer email)
          APPLE_ID="your.email@example.com"
          
          # Fetch app data from App Store
          APP_LIST=$(curl -s "https://itunes.apple.com/lookup?attributeName=yassine-benkhay/&attributeValue=benkhayyassine8@gmail.com&entity=software&limit=10&sort=recent" | tr -d '\000')
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch data from iTunes API"
            exit 1
          fi
          
          # Format the app list
          FORMATTED_LIST=$(echo "$APP_LIST" | jq -r '.results[] | select(.kind == "software") | "- [" + .trackName + "](" + .trackViewUrl + ") - " + .description[0:100] + "..."')
          
          if [ -z "$FORMATTED_LIST" ]; then
            echo "No apps found or empty response"
            exit 1
          fi
          
          # Update README.md
          sed -i '/<!-- IOS-APP-LIST:START -->/,/<!-- IOS-APP-LIST:END -->/c\<!-- IOS-APP-LIST:START -->\n'"$FORMATTED_LIST"'\n<!-- IOS-APP-LIST:END -->' README.md
      
      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Updated README with latest iOS apps" || exit 0
          git push
