name: Latest wordpress posts
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */2 * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with last blog posts from my blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://yassinebenkhay.com/feed"
